name: food_delivery_kandarbite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  collection: ^1.18.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "lib/assets/images/logo.png"
  min_sdk_android: 23 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
  - lib/assets/images/nasi/
  - lib/assets/images/drinks/
  - lib/assets/images/


